[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "WaterOptim"
authors = [{name = "Romdhana", email = "hedi.romdhana@agroparistech.fr"}]
dynamic = ["version", "description"]
